server:
  port: 9081
spring:
  application:
    name: wx-job-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
     encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/wxjob?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: wyy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
