server:
  port: 8080
spring:
  application:
    name: wx-job-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
     encoding:
      charset: UTF-8
      enabled: true
      force: true